[1pt] PR: ESRI CRS's error out
NOAA-OWP/ras2fim pull request #103
Opened 2023-07-20 21:32 UTC by EmilyDeardorff

Previously, ras2fim could only accommodate projections in the EPSG format. This PR is a quick fix to how the projection is processed to accommodate projection codes in the ESRI format.

### Changes  

- `src/ras2fim.py`: Replaced `CRS.from_epsg` with `CRS.from_string` in order to accommodate ESRI projections.
- `src/shared_functions.py`: Edited error message for clarity.

### Testing

- Tested on HUC 12040101, which uses an ESRI projection. The 'unable to find projection' error no longer occurred after the fix.

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [ ] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [ ] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

2023-07-20 23:35 UTC, RobHanna-NOAA submitted a review, later dismissed
There are other bugs in place blocking a full ras2fim run on some models, but I was able to validate her fix by doing a print statement and a "pre" and "post" code change to ensure the value that is being affected here "model_units" is the same in both scenarios. This fully validates that particular fix.

2023-07-20 23:35 UTC, RobHanna-NOAA commented
Updates.. sorry.. Emily. Can you add your Changelog update to this?

2023-07-20 23:39 UTC, RobHanna-NOAA approved these changes
I noticed a small typo that would likely create a problem when we can test meters at some point.

2023-07-21 13:50 UTC, RobHanna-NOAA requested changes
I was able to get it to work with 12040101 - ESRI:102739, but now it fails on 12090301 - ESPG:2277.  More review is required.

2023-07-23 00:49 UTC, AliForghani-NOAA commented on src/shared_functions.py
Rob, 
Are you sure this will work. 'metre' has not been a typo and I intentionally used it.

2023-07-23 18:51 UTC, RobHanna-NOAA commented on src/shared_functions.py
No. I am sorry. I thought it was a typo and should have asked. I fixed it back.

2023-07-24 15:16 UTC, RobHanna-NOAA approved these changes

2023-07-24 15:17 UTC, merged